@ECHO off
setlocal enabledelayedexpansion
REM ##################################################################################
REM 
REM	@name:		deploy-to-tomcat-balancer.bat
REM @created: 16.10.2013
REM @author: 	YND
REM
REM Script for deployment of artifacts to Tomcat
REM
REM Jenkins parameter(s) used: 
REM 	- JOB_NAME 			= Used to create temp app context directory
REM 	- TARGET_ENV 		= DEV1, DEV2, ST1, ST2, QA1, QA2, BAKQA1, BAKQA2
REM 	- CONTEXT_ROOT 	= '-','-agsc-', '-scpc'
REM 
REM Input parameter(s):
REM 	- %1 = APPLICATION 	
REM 	- %2 = WEBAPP_NAME to deploy
REM 
REM This scripts uses:
REM 	- generate-context-file.bat
REM		- deploy-to-tomcat-balancer-node.bat
REM 		- enable-disable-webapp.ps1
REM 
REM ##################################################################################
set _APPLICATION=%1
set _INPUT_PARAM=%2

REM Evaluate input parameters argument
set INPUT_OK=true
if %TARGET_ENV%X==X set INPUT_OK=false
if %_INPUT_PARAM%X==X set INPUT_OK=false

if %INPUT_OK%==false (
	echo [ERROR]
	echo [ERROR] Input parameters missing in %0
	echo [ERROR]
	goto failure	
)

set _PORT_PREFIX=
if "%_APPLICATION%"=="eboss" (
	set _PORT_PREFIX=80
) else if "%_APPLICATION%"=="escp" (
	set _PORT_PREFIX=81
) else (
  goto FAILURE
)

set _WEBAPP_NAME=%_INPUT_PARAM%%CONTEXT_ROOT%web
SET _INSTANCES_BASE=tomcat-%_APPLICATION%-instances

echo.
echo "WEBAPP_NAME=%_WEBAPP_NAME%"
echo.
REM ----------
REM CONFIGURATION START
REM ----------

REM Configuration of hosts, directories, and services for the separate environments
SET _DEV1_HOST=st-w4184
SET _DEV1_HOST_URL=eboss-dev.statoil.no
SET _DEV1_INSTANCE_NODE_1=Dev1_1
SET _DEV1_INSTANCE_NODE_2=Dev1_2
SET _DEV1_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-dev1-1
SET _DEV1_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-dev1-2
SET _DEV1_SERVICE_PORT_NODE_1=%_PORT_PREFIX%01
SET _DEV1_SERVICE_PORT_NODE_2=%_PORT_PREFIX%02

SET _DEV2_HOST=st-w4184
SET _DEV2_HOST_URL=eboss-dev.statoil.no
SET _DEV2_INSTANCE_NODE_1=Dev2_1
SET _DEV2_INSTANCE_NODE_2=Dev2_2
SET _DEV2_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-dev2-1
SET _DEV2_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-dev2-2
SET _DEV2_SERVICE_PORT_NODE_1=%_PORT_PREFIX%03
SET _DEV2_SERVICE_PORT_NODE_2=%_PORT_PREFIX%04

SET _ST1_HOST=st-tw666
SET _ST1_HOST_URL=eboss-st.statoil.no
SET _ST1_INSTANCE_NODE_1=ST1_1
SET _ST1_INSTANCE_NODE_2=ST1_2
SET _ST1_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-st1-1
SET _ST1_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-st1-2
SET _ST1_SERVICE_PORT_NODE_1=%_PORT_PREFIX%01
SET _ST1_SERVICE_PORT_NODE_2=%_PORT_PREFIX%02

SET _ST2_HOST=st-tw666
SET _ST2_HOST_URL=eboss-st.statoil.no
SET _ST2_INSTANCE_NODE_1=ST2_1
SET _ST2_INSTANCE_NODE_2=ST2_1
SET _ST2_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-st2-1
SET _ST2_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-st2-2
SET _ST2_SERVICE_PORT_NODE_1=%_PORT_PREFIX%03
SET _ST2_SERVICE_PORT_NODE_2=%_PORT_PREFIX%04

REM QA1 (QA Release)
SET _QA1_HOST_NODE_1=st-w4196
SET _QA1_HOST_NODE_2=st-w4209
SET _QA1_HOST_URL=eboss-qa.statoil.no
SET _QA1_INSTANCE_NODE_1=QA1_1
SET _QA1_INSTANCE_NODE_2=QA1_2
SET _QA1_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-qa1-1
SET _QA1_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-qa1-2
SET _QA1_SERVICE_PORT_NODE_1=%_PORT_PREFIX%01
SET _QA1_SERVICE_PORT_NODE_2=%_PORT_PREFIX%02

REM QA2 (QA Prod)
SET _QA2_HOST_NODE_1=st-w4196
SET _QA2_HOST_NODE_2=st-w4209
SET _QA2_HOST_URL=eboss-qa.statoil.no
SET _QA2_INSTANCE_NODE_1=QA2_1
SET _QA2_INSTANCE_NODE_2=QA2_2
SET _QA2_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-qa2-1
SET _QA2_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-qa2-2
SET _QA2_SERVICE_PORT_NODE_1=%_PORT_PREFIX%03
SET _QA2_SERVICE_PORT_NODE_2=%_PORT_PREFIX%04

REM BAKU QA1 (BAKU QA Release)
SET _BAKU_QA1_HOST_NODE_1=bak-w27
SET _BAKU_QA1_HOST_NODE_2=bak-w28
SET _BAKU_QA1_HOST_URL=eboss-qa.statoil.no
SET _BAKU_QA1_INSTANCE_NODE_1=QA1_1
SET _BAKU_QA1_INSTANCE_NODE_2=QA1_2
SET _BAKU_QA1_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-qa1-1
SET _BAKU_QA1_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-qa1-2
SET _BAKU_QA1_SERVICE_PORT_NODE_1=%_PORT_PREFIX%01
SET _BAKU_QA1_SERVICE_PORT_NODE_2=%_PORT_PREFIX%02

REM BAKU QA2 (BAKU QA Prod)
SET _BAKU_QA2_HOST_NODE_1=bak-w27
SET _BAKU_QA2_HOST_NODE_2=bak-w28
SET _BAKU_QA2_HOST_URL=eboss-qa.statoil.no
SET _BAKU_QA2_INSTANCE_NODE_1=QA2_1
SET _BAKU_QA2_INSTANCE_NODE_2=QA2_2
SET _BAKU_QA2_SERVICE_NODE_1=Tomcat6-%_APPLICATION%-qa2-1
SET _BAKU_QA2_SERVICE_NODE_2=Tomcat6-%_APPLICATION%-qa2-2
SET _BAKU_QA2_SERVICE_PORT_NODE_1=%_PORT_PREFIX%03
SET _BAKU_QA2_SERVICE_PORT_NODE_2=%_PORT_PREFIX%04


SET _MULTIPLE_SERVER_ENVIRONMENT=false

REM Setting target service/host/instance based on TARGET_ENV (specified as input to the job)
if "%TARGET_ENV%"=="DEV1" (  
  SET _TARGET_HOST_NODE_1=%_DEV1_HOST%
  SET _TARGET_HOST_URL=%_DEV1_HOST_URL%
  SET _TARGET_INSTANCE_NODE_1=%_DEV1_INSTANCE_NODE_1%
  SET _TARGET_INSTANCE_NODE_2=%_DEV1_INSTANCE_NODE_2%
  SET _TARGET_SERVICE_NODE_1=%_DEV1_SERVICE_NODE_1%
  SET _TARGET_SERVICE_NODE_2=%_DEV1_SERVICE_NODE_2%
  SET _TARGET_SERVICE_PORT_NODE_1=%_DEV1_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_DEV1_SERVICE_PORT_NODE_2%
) else if "%TARGET_ENV%"=="DEV2" (  
  SET _TARGET_HOST_NODE_1=%_DEV2_HOST%
  SET _TARGET_HOST_URL=%_DEV2_HOST_URL%
  SET _TARGET_INSTANCE_NODE_1=%_DEV2_INSTANCE_NODE_1%
  SET _TARGET_INSTANCE_NODE_2=%_DEV2_INSTANCE_NODE_2%
  SET _TARGET_SERVICE_NODE_1=%_DEV2_SERVICE_NODE_1%
  SET _TARGET_SERVICE_NODE_2=%_DEV2_SERVICE_NODE_2%
  SET _TARGET_SERVICE_PORT_NODE_1=%_DEV2_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_DEV2_SERVICE_PORT_NODE_2%  
) else if "%TARGET_ENV%"=="ST1" (  
  SET _TARGET_HOST_NODE_1=%_ST1_HOST%
  SET _TARGET_HOST_URL=%_ST1_HOST_URL%
  SET _TARGET_INSTANCE_NODE_1=%_ST1_INSTANCE_NODE_1%
  SET _TARGET_INSTANCE_NODE_2=%_ST1_INSTANCE_NODE_2%
  SET _TARGET_SERVICE_NODE_1=%_ST1_SERVICE_NODE_1%
  SET _TARGET_SERVICE_NODE_2=%_ST1_SERVICE_NODE_2%
  SET _TARGET_SERVICE_PORT_NODE_1=%_ST1_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_ST1_SERVICE_PORT_NODE_2%
) else if "%TARGET_ENV%"=="ST2" (  
  SET _TARGET_HOST_NODE_1=%_ST1_HOST%
  SET _TARGET_HOST_URL=%_ST2_HOST_URL%
  SET _TARGET_INSTANCE_NODE_1=%_ST2_INSTANCE_NODE_1%
  SET _TARGET_INSTANCE_NODE_2=%_ST2_INSTANCE_NODE_2%
  SET _TARGET_SERVICE_NODE_1=%_ST2_SERVICE_NODE_1%
  SET _TARGET_SERVICE_NODE_2=%_ST2_SERVICE_NODE_2%
  SET _TARGET_SERVICE_PORT_NODE_1=%_ST2_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_ST2_SERVICE_PORT_NODE_2%
) else if "%TARGET_ENV%"=="QA1" (  
  SET _TARGET_HOST_NODE_1=%_QA1_HOST_NODE_1%
  SET _TARGET_HOST_NODE_2=%_QA1_HOST_NODE_2%
  SET _TARGET_HOST_URL=%_QA1_HOST_URL%
  SET _TARGET_INSTANCE_NODE_1=%_QA1_INSTANCE_NODE_1%
  SET _TARGET_INSTANCE_NODE_2=%_QA1_INSTANCE_NODE_2%
  SET _TARGET_SERVICE_NODE_1=%_QA1_SERVICE_NODE_1%
  SET _TARGET_SERVICE_NODE_2=%_QA1_SERVICE_NODE_2%
  SET _TARGET_SERVICE_PORT_NODE_1=%_QA1_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_QA1_SERVICE_PORT_NODE_2%
  SET _MULTIPLE_SERVER_ENVIRONMENT=true
) else if "%TARGET_ENV%"=="QA2" (  
  SET _TARGET_HOST_NODE_1=%_QA2_HOST_NODE_1%
	SET _TARGET_HOST_NODE_2=%_QA2_HOST_NODE_2%
	SET _TARGET_HOST_URL=%_QA2_HOST_URL%
	SET _TARGET_INSTANCE_NODE_1=%_QA2_INSTANCE_NODE_1%
	SET _TARGET_INSTANCE_NODE_2=%_QA2_INSTANCE_NODE_2%
	SET _TARGET_SERVICE_NODE_1=%_QA2_SERVICE_NODE_1%
	SET _TARGET_SERVICE_NODE_2=%_QA2_SERVICE_NODE_2%
	SET _TARGET_SERVICE_PORT_NODE_1=%_QA2_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_QA2_SERVICE_PORT_NODE_2%
  SET _MULTIPLE_SERVER_ENVIRONMENT=true
) else if "%TARGET_ENV%"=="BAKQA2" (  
  SET _TARGET_HOST_NODE_1=%_BAKU_QA2_HOST_NODE_1%
	SET _TARGET_HOST_NODE_2=%_BAKU_QA2_HOST_NODE_2%
	SET _TARGET_HOST_URL=%_BAKU_QA2_HOST_URL%
	SET _TARGET_INSTANCE_NODE_1=%_BAKU_QA2_INSTANCE_NODE_1%
	SET _TARGET_INSTANCE_NODE_2=%_BAKU_QA2_INSTANCE_NODE_2%
	SET _TARGET_SERVICE_NODE_1=%_BAKU_QA2_SERVICE_NODE_1%
	SET _TARGET_SERVICE_NODE_2=%_BAKU_QA2_SERVICE_NODE_2%
	SET _TARGET_SERVICE_PORT_NODE_1=%_BAKU_QA2_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_BAKU_QA2_SERVICE_PORT_NODE_2%
  SET _MULTIPLE_SERVER_ENVIRONMENT=true
) else if "%TARGET_ENV%"=="BAKPROD" (  
  SET _TARGET_HOST_NODE_1=%_BAKU_PROD_HOST_NODE_1%
	SET _TARGET_HOST_NODE_2=%_BAKU_PROD_HOST_NODE_2%
	SET _TARGET_HOST_URL=%_BAKU_PROD_HOST_URL%
	SET _TARGET_INSTANCE_NODE_1=%_BAKU_PROD_INSTANCE_NODE_1%
	SET _TARGET_INSTANCE_NODE_2=%_BAKU_PROD_INSTANCE_NODE_2%
	SET _TARGET_SERVICE_NODE_1=%_BAKU_PROD_SERVICE_NODE_1%
	SET _TARGET_SERVICE_NODE_2=%_BAKU_PROD_SERVICE_NODE_2%
	SET _TARGET_SERVICE_PORT_NODE_1=%_BAKU_PROD_SERVICE_PORT_NODE_1%
  SET _TARGET_SERVICE_PORT_NODE_2=%_BAKU_PROD_SERVICE_PORT_NODE_2%
  SET _MULTIPLE_SERVER_ENVIRONMENT=true
) else (
  goto FAILURE
)

REM ----------
REM CONFIGURATION END
REM ----------

REM Create temporary app-context on deployment server if not exists
dir \\%_TARGET_HOST_NODE_1%\%_INSTANCES_BASE%\%JOB_NAME%-app-context >nul 2>nul
if errorlevel 1 (
  echo "Create \\%_TARGET_HOST_NODE_1%\%_INSTANCES_BASE%\%JOB_NAME%-app-context"
	mkdir \\%_TARGET_HOST_NODE_1%\%_INSTANCES_BASE%\%JOB_NAME%-app-context
)

REM Generate context file for application
cd
set _CUR_DIR=%cd%
echo tomcat-config\%_APPLICATION%\context
cd tomcat-config\%_APPLICATION%\context
echo %SCRIPT_HOME%\Common\generate-context-file.bat %_WEBAPP_NAME%-context-template.xml %_APPLICATION% %TARGET_ENV% %_TARGET_HOST_NODE_1%
call %SCRIPT_HOME%\Common\generate-context-file.bat %_WEBAPP_NAME%-context-template.xml %_APPLICATION% %TARGET_ENV% %_TARGET_HOST_NODE_1%
if %ERRORLEVEL% NEQ 0 goto FAILURE

REM Change directory back to current
cd %_CUR_DIR%

SET _TARGET_INSTANCE_BASE_HOST_1_NODE_1=\\%_TARGET_HOST_NODE_1%\%_INSTANCES_BASE%\%_TARGET_INSTANCE_NODE_1%
SET _TARGET_INSTANCE_BASE_HOST_1_NODE_2=\\%_TARGET_HOST_NODE_1%\%_INSTANCES_BASE%\%_TARGET_INSTANCE_NODE_2%

echo.
echo "WEBAPP_NAME=%_WEBAPP_NAME%"
echo "SERVICEPORT NODE 1=%_TARGET_SERVICE_PORT_NODE_1%
echo "SERVICEPORT NODE 2=%_TARGET_SERVICE_PORT_NODE_2%
echo.

REM HOST1 NODE1
echo.
echo "[INFO] HOST\SERVICE: %_TARGET_HOST_NODE_1%\%_TARGET_SERVICE_NODE_1%"
echo %SCRIPT_HOME%\Common\deploy-to-tomcat-balancer-node.bat %_APPLICATION% %_WEBAPP_NAME% %_TARGET_HOST_NODE_1% %_TARGET_SERVICE_PORT_NODE_1% %_TARGET_INSTANCE_BASE_HOST_1_NODE_1%
call %SCRIPT_HOME%\Common\deploy-to-tomcat-balancer-node.bat %_APPLICATION% %_WEBAPP_NAME% %_TARGET_HOST_NODE_1% %_TARGET_SERVICE_PORT_NODE_1% %_TARGET_INSTANCE_BASE_HOST_1_NODE_1%
if %ERRORLEVEL% NEQ 0 goto FAILURE

echo "[INFO] HOST\SERVICE: %_TARGET_HOST_NODE_1%\%_TARGET_SERVICE_NODE_1% FINISHED"

REM HOST1 NODE2
echo.
echo "[INFO] HOST/SERVICE: %_TARGET_HOST_NODE_1%\%_TARGET_SERVICE_NODE_2%"
call %SCRIPT_HOME%\Common\deploy-to-tomcat-balancer-node.bat %_APPLICATION% %_WEBAPP_NAME% %_TARGET_HOST_NODE_1% %_TARGET_SERVICE_PORT_NODE_2% %_TARGET_INSTANCE_BASE_HOST_1_NODE_2%
if %ERRORLEVEL% NEQ 0 goto FAILURE

echo "[INFO] HOST/SERVICE: %_TARGET_HOST_NODE_1%\%_TARGET_SERVICE_NODE_2% FINISHED


REM Remove temp app-context directory on deployment server 
rmdir \\%_TARGET_HOST_NODE_1%\%_INSTANCES_BASE%\%JOB_NAME%-app-context /S /Q
if %ERRORLEVEL% NEQ 0 goto failure

REM Check if this is a multiserver environment
if "%_MULTIPLE_SERVER_ENVIRONMENT%"=="true" (
	goto MULTIPLE_SERVER_ENVIRONMENT
) else (
	goto END
)

REM MULTIPLE SERVER ENVIRONMENT: QA1, QA2, BAKU QA1, BAKU QA2
:MULTIPLE_SERVER_ENVIRONMENT
echo "[INFO] Multiple Server Environment"
echo.
echo %_TARGET_HOST_NODE_2%
echo %_INSTANCES_BASE%
echo %_TARGET_INSTANCE_NODE_1%
echo %_TARGET_INSTANCE_NODE_2%
echo.

SET _TARGET_INSTANCE_BASE_HOST_2_NODE_1=\\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%_TARGET_INSTANCE_NODE_1%
SET _TARGET_INSTANCE_BASE_HOST_2_NODE_2=\\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%_TARGET_INSTANCE_NODE_2%

REM Create temporary app-context on deployment server if not exists
dir \\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%JOB_NAME%-app-context >nul 2>nul
if errorlevel 1 (
	echo "Create \\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%JOB_NAME%-app-context"
	mkdir \\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%JOB_NAME%-app-context
)


REM Generate context file for application
cd
set _CUR_DIR=%cd%
echo tomcat-config\%_APPLICATION%\context
cd tomcat-config\%_APPLICATION%\context
echo %SCRIPT_HOME%\Common\generate-context-file.bat %_WEBAPP_NAME%-context-template.xml %_APPLICATION% %TARGET_ENV% %_TARGET_HOST_NODE_2%
call %SCRIPT_HOME%\Common\generate-context-file.bat %_WEBAPP_NAME%-context-template.xml %_APPLICATION% %TARGET_ENV% %_TARGET_HOST_NODE_2%
if %ERRORLEVEL% NEQ 0 goto FAILURE

REM Change directory back to current
cd %_CUR_DIR%

SET _TARGET_INSTANCE_BASE_HOST_2_NODE_1=\\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%_TARGET_INSTANCE_NODE_1%
SET _TARGET_INSTANCE_BASE_HOST_2_NODE_2=\\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%_TARGET_INSTANCE_NODE_2%

REM HOST2 NODE 1
echo "[INFO] HOST\SERVICE: %_TARGET_HOST_NODE_2%\%_TARGET_SERVICE_NODE_1%"
call %SCRIPT_HOME%\Common\deploy-to-tomcat-balancer-node.bat %_APPLICATION%  %_WEBAPP_NAME% %_TARGET_HOST_NODE_2% %_TARGET_SERVICE_PORT_NODE_1% %_TARGET_INSTANCE_BASE_HOST_2_NODE_1%
if %ERRORLEVEL% NEQ 0 goto FAILURE

echo "[INFO] HOST\SERVICE: %_TARGET_HOST_NODE_2%\%_TARGET_SERVICE_NODE_1% FINISHED"

REM HOST2 NODE 2
echo "[INFO] HOST\SERVICE: %_TARGET_HOST_NODE_2%\%_TARGET_SERVICE_NODE_2%"
call %SCRIPT_HOME%\Common\deploy-to-tomcat-balancer-node.bat %_APPLICATION%  %_WEBAPP_NAME% %_TARGET_HOST_NODE_2% %_TARGET_SERVICE_PORT_NODE_2% %_TARGET_INSTANCE_BASE_HOST_2_NODE_2%
if %ERRORLEVEL% NEQ 0 goto FAILURE

echo "[INFO] HOST\SERVICE: %_TARGET_HOST_NODE_2%\%_TARGET_SERVICE_NODE_2% FINISHED"

REM Remove temp app-context for application on deployment server 
rmdir \\%_TARGET_HOST_NODE_2%\%_INSTANCES_BASE%\%JOB_NAME%-app-context /S /Q
if %ERRORLEVEL% NEQ 0 goto FAILURE

goto END

:FAILURE
exit 13

:END
@ECHO ON